[package]
name = "llc_cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ccg = { version = "0.1.0", path = "../ccg" }
llc_parser = { version = "0.1.0", path = "../parser" }
